#include "Permutation.h"
#include "StabChainMain.h"
#include "nsi.h"
#include "gmpxx.h"
#include <fstream>

int main(int argc, char *argv[])
{
  try {
    using Telt = permutalib::DoubleSidedPerm;
    using Tint = mpz_class;
    if (argc != 3 && argc != 2) {
      std::cerr << "We should have argc = 2\n";
      std::cerr << "GapCanonicalImage [EXMP] [OutFile]\n";
      std::cerr << "with EXMP generated by GenerateCanonicalImage.g\n";
      throw PermutalibException{1};
    }
    std::string InputFile = argv[1];
    std::string OutputFile = "unset";
    if (argc == 3)
      OutputFile = argv[2];
    //
    std::ifstream is(InputFile);
    int nbGen, n;
    is >> nbGen;
    is >> n;
    std::vector<Telt> LGen(nbGen);
    for (int iGen=0; iGen<nbGen; iGen++) {
      std::vector<int> ePermV(n);
      for (int i=0; i<n; i++) {
	int eVal;
	is >> eVal;
	ePermV[i]=eVal;
      }
      Telt ePerm(ePermV);
      LGen[iGen] = ePerm;
    }
    std::cerr.setf(std::ios::boolalpha);
    //
    //    permutalib::StabChain<Telt> eG = permutalib::MinimalStabChain<Telt,Tint>(LGen, n);
    permutalib::StabChain<Telt> eG = permutalib::Group<Telt,Tint>(LGen, n);
    //    std::cerr << "CPP eG=" << eG << "\n";
    //
    std::cerr << "CPP |eG|=" << permutalib::Order<Telt,Tint>(eG) << "\n";
    //
    Face eFace(n);
    for (int i=0; i<n; i++) {
      int eVal;
      is >> eVal;
      eFace[i] = eVal;
    }
    Face set_can = permutalib::CanonicalImage<Telt,Tint>(eG, eFace);
    //
    std::ofstream os(OutputFile);
    os << "return [";
    int siz = set_can.count();
    int aRow = set_can.find_first();
    for (int i=0; i<siz; i++) {
      if (i > 0)
        os << ",";
      os << (aRow + 1);
      aRow = set_can.find_next(aRow);
    }
    os << "|;\n";
    std::cerr << "CPP Normal completion of the program\n";
  }
  catch (PermutalibException const& e) {
    std::cerr << "Erroneous completion of the program\n";
    exit(e.eVal);
  }
  return 0;
}
