// Copyright (C) 2022 Mathieu Dutour Sikiric <mathieu.dutour@gmail.com>
#include "Permutation.h"
#include "gmpxx.h"
#include <fstream>

#include "Group.h"

int main(int argc, char *argv[]) {
  try {
    using Tidx = uint16_t;
    //    using Telt = permutalib::DoubleSidedPerm<Tidx>;
    using Telt = permutalib::SingleSidedPerm<Tidx>;
    using Tint = mpz_class;
    using Tgroup = permutalib::Group<Telt, Tint>;
    if (argc != 3 && argc != 4) {
      std::cerr << "We should have argc = 2\n";
      std::cerr << "GapCanonicalImage [EXMP] [method] [OutFile]\n";
      std::cerr << "with EXMP generated by GenerateCanonicalImage.g\n";
      std::cerr << "Available method: CanonicalImage, StoreCanonicalImage,\n";
      std::cerr << "   CanonicalImageInitialTriv, CanonicalImageInitialTrivLimited\n";
      throw permutalib::PermutalibException{1};
    }
    std::string InputFile = argv[1];
    std::string method = argv[2];
    //
    std::ifstream is(InputFile);
    Tgroup eG = permutalib::ReadGroupFromStream<Tgroup>(is);
    std::cerr.setf(std::ios::boolalpha);
    std::cerr << "CPP |eG|=" << eG.size() << "\n";
    //
    size_t LIMIT_INITIAL_TRIV = 5000;
    std::string s;
    is >> s;
    permutalib::Face eFace = permutalib::ConvertStringToFace(s);
    auto get_can=[&]() -> permutalib::Face {
      if (method == "CanonicalImage")
        return eG.CanonicalImage(eFace);
      if (method == "StoreCanonicalImage")
        return eG.StoreCanonicalImage(eFace);
      if (method == "CanonicalImageInitialTriv")
        return eG.CanonicalImageInitialTriv(eFace);
      if (method == "CanonicalImageInitialTrivLimited")
        return eG.CanonicalImageInitialTrivLimited(eFace, LIMIT_INITIAL_TRIV);
      std::cerr << "Failed to find a matching entry\n";
      throw permutalib::PermutalibException{1};
    };
    permutalib::Face set_can = get_can();
    //
    auto prt = [&](std::ostream &os) -> void {
      os << "return [";
      size_t siz = set_can.count();
      boost::dynamic_bitset<>::size_type aRow = set_can.find_first();
      for (size_t i = 0; i < siz; i++) {
        if (i > 0)
          os << ",";
        os << (static_cast<int>(aRow) + 1);
        aRow = set_can.find_next(aRow);
      }
      os << "];\n";
    };
    if (argc == 3) {
      std::string OutputFile = argv[2];
      std::ofstream os(OutputFile);
      prt(os);
    } else {
      prt(std::cerr);
    }
    std::cerr << "CPP Normal completion of the program\n";
  } catch (permutalib::PermutalibException const &e) {
    std::cerr << "Erroneous completion of the program\n";
    exit(e.eVal);
  }
  return 0;
}
