name: CI of Permutalib

# https://help.github.com/en/articles/events-that-trigger-workflows#release-event-release
# model taken from https://github.com/mockersf/kmanb/releases
# on: release

on:
  # Every day at 5 am.
  schedule:
    - cron: "0 0 * * *"
  # Manually triggered
  workflow_dispatch:
  # Disabled right now, when a push is made on master.
jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      GMP_INCDIR: /usr/include
      GMP_CXX_LINK: "-lm -lgmp -lgmpxx"
      BOOST_INCDIR: "/usr/include"
      BOOST_LINK: "/usr/lib/x86_64-linux-gnu/libboost_serialization.a"


    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install Dependencies
        run: |
          sudo apt-get install -y libgdbm-dev libsnappy-dev make pkg-config rlwrap software-properties-common zlib1g-dev
          sudo apt-get install -y g++-11 clang-12
          sudo apt-get install -y g++ gcc gfortran
          sudo apt-get install -y cmake
          sudo apt-get install -y libgmp-dev
          sudo apt-get install -y libboost-dev libboost-mpi-dev libboost-serialization-dev

      - name: Build test code
        run: |
          ls
          echo "After ls"

          cd src_gap && make && cd ..
          echo "After compilation"
