name: CI(03) of EqSymmGroup

on:
  # Day 3 of each month at midnight UTC
  schedule:
    - cron: "0 0 3 * *"
  # Manually triggered
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      GMP_INCDIR: /usr/include
      GMP_CXX_LINK: "-lm -lgmp -lgmpxx"
      BOOST_INCDIR: "/usr/include"
      BOOST_LINK: "/usr/lib/x86_64-linux-gnu/libboost_serialization.a"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential make pkg-config
          sudo apt-get install -y libgmp-dev
          sudo apt-get install -y libboost-dev libboost-serialization-dev

      - name: Build EqSymmGroup
        run: cd src && make EqSymmGroup

      - name: Run EqSymmGroup CI
        run: |
          cd CI_tests/03_EqSymmGroup
          bash ProcessExamples.sh
          if [ ! -f "CI_CONCLUSION" ]; then
            echo "The CI test did not create the expected CI_CONCLUSION file" >&2
            exit 1
          fi
